<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Shared\Errors\**" />
    <EmbeddedResource Remove="Shared\Errors\**" />
    <None Remove="Shared\Errors\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ObligatorAssets\Commands\CreateObligatorAsset\DTOs\" />
    <Folder Include="ObligatorAssets\Commands\CreateObligatorAsset\Validators\" />
    <Folder Include="ObligatorAssets\Commands\DeleteObligatorAsset\DTOs\" />
    <Folder Include="ObligatorAssets\Commands\DeleteObligatorAsset\Validators\" />
    <Folder Include="ObligatorAssets\Commands\UpdateObligatorAsset\DTOs\" />
    <Folder Include="ObligatorAssets\Commands\UpdateObligatorAsset\Validators\" />
    <Folder Include="ObligatorAssets\Queries\DTOs\" />
    <Folder Include="ObligatorAssets\Queries\Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="PrivateEnforcement.IntegrationTests" />
	</ItemGroup>

</Project>
